### ISSUE TITLE
Escape special characters

### ISSUE THREAD

**Issue by nivalderramas** [kellya/rofi-sound#1]
My headphones have a name like "H600 [Wireless Headset] Analog Stereo" And grep ignored some special characters, I have added the flag `-F` to escape this special characters. I'm not sure if this is intentional.
Btw thanks for this tool!

**Comment by kellya** [comment]
I have merged the PR.  There was nothing intentional about how I added it, only my "quick throwing it together" missing the possibility that names could have weird characters in them :)  Thank you for the fix.
